### PR TITLE
v1.8.0

### PR DESCRIPTION
**Pull request by davidMkCb**
v1.8.0

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by urischwartz-cb — APPROVED** [review]

**Comment by danhaive** [comment]
I am having an import issue with types when trying to use 1.8.0. Had to revert to 1.7.0.

**Comment by davidMkCb** [comment]
> I am having an import issue with types when trying to use 1.8.0. Had to revert to 1.7.0.

hey @danhaive, thank you for reporting! Could you give a bit more details into the issues you're having?

**Comment by supermarin** [comment]
```
Python 3.12.7 (main, Oct  1 2024, 02:05:46) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from coinbase import websocket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marin/code/yolo/.venv/lib/python3.12/site-packages/coinbase/websocket/__init__.py", line 6, in <module>
    from .types.websocket_response import WebsocketResponse
ModuleNotFoundError: No module named 'coinbase.websocket.types'
>>> from coinbase import rest
>>> 
```

**Comment by davidMkCb** [comment]
hey @supermarin, thanks for reporting the issues! We're working on the fixes right now.

**Comment by davidMkCb** [comment]
Hey @supermarin @danhaive, released v1.8.1 addressing these issues!

**Pull request merged**
